networks:
  deploy-guide:
    driver: bridge

services:
  taskmetrics:
    image: taskmetrics
    container_name: taskmetrics
    build:
      context: .
      dockerfile: TaskMetrics/Dockerfile
    ports:
      - "${SERVER_PORT}:8080"
      - "8081:8081"
    networks:
      - deploy-guide
    depends_on:
      - postgres-db
    command: ["dotnet", "ef", "database update"]
  
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - deploy-guide
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
